---
- hosts: localhost
  vars:
    mongo_user: root
    mongo_password: example
  tasks:
    - name: Gather information about databases and their total size
      community.mongodb.mongodb_info:
        login_user: "{{ mongo_user }}"
        login_password: "{{ mongo_password }}"
        filter: databases, total_size
      register: mongo_info
    
    - name: Output information about databases and their total size
      debug:
        msg: "{{ mongo_info }}"

