---
- hosts: localhost
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.systemd:
        name: nginx.service
        state: started
        enabled: yes
    
    - name: create folder for webapp
      ansible.builtin.file:
        path: /usr/share/nginx/html/webapp
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: create index page
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/webapp/index.html
        owner: root
        group: root
        mode: '0644'