---
- hosts: webserver
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    
    - name: create folder for webapp
      ansible.builtin.file:
        path: /usr/share/nginx/html/webapp
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: create index page
      ansible.builtin.template:
        src: templates/webapp_index.html.j2
        dest: /usr/share/nginx/html/webapp/index.html
        owner: root
        group: root
        mode: '0644'